# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie_pubsub.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'movie_pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12movie_pubsub.proto\x12\x0bmoviepubsub\"b\n\x10SubscribeRequest\x12\r\n\x05movie\x18\x01 \x01(\t\x12&\n\x06topics\x18\x02 \x03(\x0e\x32\x16.moviepubsub.TopicType\x12\x17\n\x0fsubscriber_name\x18\x03 \x01(\t\"\x89\x01\n\x07Message\x12\r\n\x05movie\x18\x01 \x01(\t\x12%\n\x05topic\x18\x02 \x01(\x0e\x32\x16.moviepubsub.TopicType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x14\n\x0crating_value\x18\x06 \x01(\x02\"}\n\x0ePublishRequest\x12\r\n\x05movie\x18\x01 \x01(\t\x12%\n\x05topic\x18\x02 \x01(\x0e\x32\x16.moviepubsub.TopicType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x14\n\x0crating_value\x18\x05 \x01(\x02\"P\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x1c\n\x14subscribers_notified\x18\x03 \x01(\x05*P\n\tTopicType\x12\n\n\x06REVIEW\x10\x00\x12\n\n\x06RATING\x10\x01\x12\x0e\n\nACTOR_NEWS\x10\x02\x12\x0b\n\x07TRAILER\x10\x03\x12\x0e\n\nBOX_OFFICE\x10\x04\x32\x97\x01\n\x0bMoviePubSub\x12\x42\n\tSubscribe\x12\x1d.moviepubsub.SubscribeRequest\x1a\x14.moviepubsub.Message0\x01\x12\x44\n\x07Publish\x12\x1b.moviepubsub.PublishRequest\x1a\x1c.moviepubsub.PublishResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICTYPE']._serialized_start=484
  _globals['_TOPICTYPE']._serialized_end=564
  _globals['_SUBSCRIBEREQUEST']._serialized_start=35
  _globals['_SUBSCRIBEREQUEST']._serialized_end=133
  _globals['_MESSAGE']._serialized_start=136
  _globals['_MESSAGE']._serialized_end=273
  _globals['_PUBLISHREQUEST']._serialized_start=275
  _globals['_PUBLISHREQUEST']._serialized_end=400
  _globals['_PUBLISHRESPONSE']._serialized_start=402
  _globals['_PUBLISHRESPONSE']._serialized_end=482
  _globals['_MOVIEPUBSUB']._serialized_start=567
  _globals['_MOVIEPUBSUB']._serialized_end=718
# @@protoc_insertion_point(module_scope)
