# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import movie_pubsub_pb2 as movie__pubsub__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in movie_pubsub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MoviePubSubStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/moviepubsub.MoviePubSub/Subscribe',
                request_serializer=movie__pubsub__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=movie__pubsub__pb2.Message.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/moviepubsub.MoviePubSub/Publish',
                request_serializer=movie__pubsub__pb2.PublishRequest.SerializeToString,
                response_deserializer=movie__pubsub__pb2.PublishResponse.FromString,
                _registered_method=True)


class MoviePubSubServicer:
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Assina um filme (com filtro opcional de tópicos) e recebe um stream
        contínuo de mensagens publicadas a partir do momento da inscrição.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Publica uma nova mensagem em um tópico de um filme.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviePubSubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=movie__pubsub__pb2.SubscribeRequest.FromString,
                    response_serializer=movie__pubsub__pb2.Message.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=movie__pubsub__pb2.PublishRequest.FromString,
                    response_serializer=movie__pubsub__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moviepubsub.MoviePubSub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moviepubsub.MoviePubSub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoviePubSub:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/moviepubsub.MoviePubSub/Subscribe',
            movie__pubsub__pb2.SubscribeRequest.SerializeToString,
            movie__pubsub__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moviepubsub.MoviePubSub/Publish',
            movie__pubsub__pb2.PublishRequest.SerializeToString,
            movie__pubsub__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
